name = "browsable-object-example"
main = "example.ts"
compatibility_date = "2025-07-08"
route.custom_domain = true
route.pattern = "browsable.itscooldo.com"
# Use the local preview to test this
[dev]
port = 3000

# Define the durable object
[[durable_objects.bindings]]
name = "MyDO"
class_name = "MyDO"

# Set up a migration to enable the SQLite database
[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyDO"]
